name: Tests on Rocky Linux 8

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - uses: actions/checkout@v4
    - name: Where Am I?
      run: |
        ls ${{github.workspace}}/
        
    - name: Run Buil CentOS 8 latest
      run: |
        ${{github.workspace}}/build_lustre_centos8_latest.sh
